=== thaonguyen296/Lab2/Part4.dtd
<!ELEMENT FPTAptech (Student*)>
<!ELEMENT Student (Name,Sex,Age)>
<!ATTLIST Student Sex (Female|Male) "Female">
<!ELEMENT Name (FName,LName)>
<!ELEMENT Age (#PCDATA)>
<!ELEMENT FName (#PCDATA)>
<!ELEMENT LName (#PCDATA)>

=== thaonguyen296/Lab2/Part4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE FPTAptech SYSTEM "Part4.dtd">
<FPTAptech>
   <Student Sex="Female">
      <Name>
         <FName>Dinh</FName>
         <LName>Anh</LName>
      </Name>
      <Age>18</Age>
   </Student>
   <Student Sex="Female">
      <Name>
         <FName>Phan</FName>
         <LName>Tu</LName>
      </Name>
      <Age>22</Age>
   </Student>
   <Student Sex="Male">
      <Name>
         <FName>Kiet</FName>
         <LName>Do</LName>
      </Name>
      <Age>15</Age>
   </Student>
</FPTAptech>
